### ISSUE TITLE
[ErgodicSoaring] TODO Workpackages

### ISSUE THREAD

**Issue by Jaeyoung-Lim** [Jaeyoung-Lim/mav_soaring#19]
**Flight control**
- [x] Add back support for soaring set points on PX4 (https://github.com/PX4/PX4-Autopilot/pull/17940)
- [x] Integrate Trajectory tracking controller for gliders (https://github.com/ethz-asl/ethzasl_fw_px4/pull/39)

**Ergodic Control**
- [x] Integration of `grid_map` into this package (https://github.com/Jaeyoung-Lim/mav-soaring/pull/21)
- [x] Fourier transform of gridmap probability distribution (https://github.com/Jaeyoung-Lim/mav-soaring/pull/21) 
- [x] Fourier transform of trajectory to distribution (https://github.com/Jaeyoung-Lim/mav-soaring/pull/22)
- [x] Visualize ergodicity
- Implementation of projection operator based trajectory optimization 
  - [x] Get Gradient Direction(https://github.com/Jaeyoung-Lim/mav-soaring/pull/24 https://github.com/Jaeyoung-Lim/mav-soaring/pull/25 https://github.com/Jaeyoung-Lim/mav-soaring/pull/26)
  - [x] Projection Operator (https://github.com/Jaeyoung-Lim/mav-soaring/pull/28)
